hydra:
  run:
    dir: ./result
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  launcher:
    _target_: hydra._internal.core_plugins.basic_launcher.BasicLauncher
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
    params: null
  help:
    app_name: ${hydra.job.name}
    header: '${hydra.help.app_name} is powered by Hydra.

      '
    footer: 'Powered by Hydra (https://hydra.cc)

      Use --hydra-help to view Hydra specific help

      '
    template: '${hydra.help.header}

      == Configuration groups ==

      Compose your configuration from those groups (group=option)


      $APP_CONFIG_GROUPS


      == Config ==

      Override anything in the config (foo.bar=value)


      $CONFIG


      ${hydra.help.footer}

      '
  hydra_help:
    template: 'Hydra (${hydra.runtime.version})

      See https://hydra.cc for more info.


      == Flags ==

      $FLAGS_HELP


      == Configuration groups ==

      Compose your configuration from those groups (For example, append hydra/job_logging=disabled
      to command line)


      $HYDRA_CONFIG_GROUPS


      Use ''--cfg hydra'' to Show the Hydra config.

      '
    hydra_help: ???
  hydra_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][HYDRA] %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers:
      - console
    loggers:
      logging_example:
        level: DEBUG
    disable_existing_loggers: false
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
    root:
      level: INFO
      handlers:
      - console
      - file
    disable_existing_loggers: false
  env: {}
  mode: MULTIRUN
  searchpath: []
  callbacks: {}
  output_subdir: .hydra
  overrides:
    hydra:
    - hydra.mode=MULTIRUN
    task:
    - +model_config=local
    - +adv_demonstration=backdoor_exp1_addsent_setup1,backdoor_exp1_addsent_setup2,backdoor_exp1_addsent_setup3,backdoor_exp1_badword_setup1,backdoor_exp1_badword_setup2,backdoor_exp1_badword_setup3,backdoor_exp1_stylebkd_setup1,backdoor_exp1_stylebkd_setup2,backdoor_exp1_stylebkd_setup3,backdoor_exp1_synbkd_setup1,backdoor_exp1_synbkd_setup2,backdoor_exp1_synbkd_setup3,counterfactual_control_raising_cf,counterfactual_control_raising,counterfactual_irregular_form_cf,counterfactual_irregular_form,counterfactual_main_verb_cf,counterfactual_main_verb,counterfactual_snli_hypothesis_cf,counterfactual_snli_hypothesis,counterfactual_snli_premise_cf,counterfactual_snli_premise,counterfactual_syntactic_category_cf,counterfactual_syntactic_category,spurious_adverb_entail-bias,spurious_adverb_non-entail-bias,spurious_adverb_zero,spurious_embedded_under_verb_entail-bias,spurious_embedded_under_verb_non-entail-bias,spurious_embedded_under_verb_zero,spurious_l_relative_clause_entail-bias,spurious_l_relative_clause_non-entail-bias,spurious_l_relative_clause_zero,spurious_passive_entail-bias,spurious_passive_non-entail-bias,spurious_passive_zero,spurious_PP_entail-bias,spurious_PP_non-entail-bias,spurious_PP_zero,spurious_s_relative_clause_entail-bias,spurious_s_relative_clause_non-entail-bias,spurious_s_relative_clause_zero
  job:
    name: main
    chdir: false
    override_dirname: +adv_demonstration=backdoor_exp1_addsent_setup1,backdoor_exp1_addsent_setup2,backdoor_exp1_addsent_setup3,backdoor_exp1_badword_setup1,backdoor_exp1_badword_setup2,backdoor_exp1_badword_setup3,backdoor_exp1_stylebkd_setup1,backdoor_exp1_stylebkd_setup2,backdoor_exp1_stylebkd_setup3,backdoor_exp1_synbkd_setup1,backdoor_exp1_synbkd_setup2,backdoor_exp1_synbkd_setup3,counterfactual_control_raising_cf,counterfactual_control_raising,counterfactual_irregular_form_cf,counterfactual_irregular_form,counterfactual_main_verb_cf,counterfactual_main_verb,counterfactual_snli_hypothesis_cf,counterfactual_snli_hypothesis,counterfactual_snli_premise_cf,counterfactual_snli_premise,counterfactual_syntactic_category_cf,counterfactual_syntactic_category,spurious_adverb_entail-bias,spurious_adverb_non-entail-bias,spurious_adverb_zero,spurious_embedded_under_verb_entail-bias,spurious_embedded_under_verb_non-entail-bias,spurious_embedded_under_verb_zero,spurious_l_relative_clause_entail-bias,spurious_l_relative_clause_non-entail-bias,spurious_l_relative_clause_zero,spurious_passive_entail-bias,spurious_passive_non-entail-bias,spurious_passive_zero,spurious_PP_entail-bias,spurious_PP_non-entail-bias,spurious_PP_zero,spurious_s_relative_clause_entail-bias,spurious_s_relative_clause_non-entail-bias,spurious_s_relative_clause_zero,+model_config=local
    id: ???
    num: ???
    config_name: config
    env_set: {}
    env_copy: []
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys: []
  runtime:
    version: 1.3.2
    version_base: '1.2'
    cwd: /data/maxiaoxiao/security/DecodingTrust
    config_sources:
    - path: hydra.conf
      schema: pkg
      provider: hydra
    - path: dt.configs
      schema: pkg
      provider: main
    - path: ''
      schema: structured
      provider: schema
    output_dir: ???
    choices:
      model_config: local
      hydra/env: default
      hydra/callbacks: null
      hydra/job_logging: default
      hydra/hydra_logging: default
      hydra/hydra_help: default
      hydra/help: default
      hydra/sweeper: basic
      hydra/launcher: basic
      hydra/output: default
  verbose: false
model_config:
  model: hf//data/maxiaoxiao/security/model/Llama-2-7b-chat-hf
  type: CHAT
  conv_template: llama-2
  model_loader: HF
  torch_dtype: FLOAT16
  trust_remote_code: true
  use_auth_token: true
  disable_exllama: false
  inject_fused_attention: true
  quant_file: null
  tokenizer_name: null
  device_map: auto
disable_sys_prompt: false
key: null
dry_run: false
advglue: null
adv_demonstration: null
fairness: null
machine_ethics: null
ood: null
privacy: null
stereotype: null
toxicity: null
